version: '3'

services:
  
  otel-collector:
    container_name: otelcol
    image: otel/opentelemetry-collector-contrib:0.83.0
    command:
      - --config=/etc/otelcol-contrib/config.yaml
    volumes:
      - ./otel/config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      # OTLP gRPC receiver
      - 4317:4317
      # OTLP http receiver
      - 4318:4318
      # OTEL COLLECTOR EXPORTER Prometheus exposed endpoint & port for metrics(From RECIEVERS)
      # to be pulled by Prometheus scraper Job.
      - 8889
      # OTEL COLLECTOR METRICS(ITSELF) exposed endpoint & port for prometheus scraper Job.
      # (If we want to get the collectors metrics.)
      # - 8888


  # Event monitoring and alerting
  #  - Records metrics in a time series database built using an HTTP PULL model
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.44.0
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  # FOR TRACING
  tempo:
    image: grafana/tempo:2.2.2
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./grafana/grafana.ini:/etc/grafana.ini:ro
      - ./grafana/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./.tmp/tempo:/tmp/tempo
    ports:
      - 3200   # tempo
      - 4318   # otplp http

  # FOR USER INTERFACE & METRICS
  grafana:
    container_name: grafana
    image: grafana/grafana:9.4.3
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    ports:
      - 3000:3000

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  # jaeger:
  #   image: jaegertracing/all-in-one
  #   container_name: jaeger
  #   ports:
  #     - 16686:16686
  #     - 14268

  loki:
    container_name: loki
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100