apiVersion: 1

datasources:
  - name: Prometheus
    orgId: 1
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Tempo
    orgId: 1
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'Prometheus'
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
        tags: [ { key: 'service.name', value: 'appName' } ]
      tracesToMetrics:
        datasourceUid: 'Prometheus'
        tags: [{ key: 'service.name', value: 'service' }, { key: 'org' }, { key: 'method' }, { key: 'uri' }, { key: 'outcome' }, { key: 'status' }, { key: 'exception' }]
        queries:
          - name: 'Throughput'
            query: 'sum(rate(http_server_requests_seconds_count{$$__tags}[$$__rate_interval]))'
          - name: 'Latency'
            query: 'histogram_quantile(1.00, sum(rate(http_server_requests_seconds_bucket{$$__tags}[$$__rate_interval])) by (le))'
        spanStartTimeShift: '-10m'
        spanEndTimeShift: '10m'


  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 50
      derivedFields:
        - datasourceUid: Tempo
          matcherRegex: '\w+ \[.+,(\w*),\w*\] \d+'
          name: traceId
          url: $${__value.raw}