receivers:
  otlp:
    protocols:
      http: # :4318

processors:
  # batch metrics before sending to reduce API usage.
  batch:
  # spanmetrics:
  #   metrics_exporter: prometheus

exporters:
  # prometheus: # metrics
  #   endpoint: 'http://prometheus:9090/api/v1/write'
  #   tls:
  #     insecure: true

  otlphttp/tracing: # tracing
    endpoint: http://tempo:4318
    tls:
      insecure: true

  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    format: proto

  jaeger:
    endpoint: http://jaeger:14250
    tls:
      insecure: true

extensions:
  # responsible for responding health checks calls on behalf of collector
  health_check:
  # fetches the collector's performance data
  pprof:
  # serves as an http endpoint that provides live debugging data about instrumented components.
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tracing, zipkin]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp]
    
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp]
